### ISSUE TITLE
Any design?

### ISSUE THREAD

**Issue by Olyno** [vlang/vbrowser#3]
Hi 👋 
The project seems amazing! Do you have any design of how the browser should looks like? (yeah, that's all, simply a question about designs ahahah)

**Comment by medvednikov** [comment]
Web browsers all have basic similar designs now.

It'll me a huge webview with tabs (vertical or horizontal) and bookmarks. Just like Chrome, just with less padding :)

**Comment by M4SSD35TRUCT10N** [comment]
Well, I don't know if anybody knows the suckless.org's [surf browser](https://surf.suckless.org/) or the servo project [browser.html](https://github.com/browserhtml/browserhtml). There's no need to do yet another FF or Chrome. Although some creature comforts would still be appreciated.

**Comment by medvednikov** [comment]
Having no tabs or bookmarks is extreme for the majority of users.

It will all be configurable.
